
function renderComments(){const root=$('comments');root.replaceChildren();if(!state.data)return;const hunk=state.data.page.items.find(item=>item.id===state.selected);const comments=hunk?(hunk.comments||[]).filter(comment=>state.topicId==='all'||comment.topicId===state.topicId):[];$('commentTitle').textContent=state.topicId==='all'?'Comments':'Comments · '+topicLabel(state.topicId);if(!hunk||!comments.length){const empty=document.createElement('div');empty.className='empty';empty.textContent=hunk?'No comments in this topic.':'Select a patch.';root.append(empty);return}for(const comment of comments){const card=document.createElement('article');card.className='comment'+(comment.resolved?' resolved':'');const meta=document.createElement('div');meta.className='meta';const author=document.createElement('b');author.textContent=comment.author&&comment.author.name?comment.author.name:'Reviewer';const topic=document.createElement('span');topic.className='topicchip';topic.textContent=topicLabel(comment.topicId);const kind=document.createElement('span');kind.className='kind';kind.textContent=comment.kind;const severity=document.createElement('span');severity.className='severity '+(comment.severity==='critical'||comment.severity==='major'?'rejected':'pending');severity.textContent=comment.severity;meta.append(author,topic,kind,severity);card.append(meta);if(comment.title){const title=document.createElement('div');title.className='comment-title';title.textContent=comment.title;card.append(title)}const body=document.createElement('div');body.className='body';body.textContent=comment.body;card.append(body);if(comment.implementationReply){const reply=document.createElement('div');reply.className='reply';reply.textContent='Implementation reply: '+comment.implementationReply;card.append(reply)}const actions=document.createElement('div');actions.className='comment-actions';actions.append(button('Reply',()=>replyComment(comment)),button(comment.resolved?'Reopen':'Resolve',()=>resolveComment(comment,!comment.resolved)));card.append(actions);root.append(card)}}
function renderCommentForm(){const select=$('commentTopic');select.replaceChildren();if(!state.data)return;for(const topic of state.data.topics){const option=document.createElement('option');option.value=topic.id;option.textContent=topic.label;select.append(option)}select.value=state.topicId!=='all'?state.topicId:(state.data.topics[0]||{}).id||''}
function render(){if(!state.data)return;renderHeader();renderTopics();renderCommentForm();$('paper').className='paper '+state.mode;if(state.mode==='final')renderFinal();else renderHunks();renderComments()}
async function loadPage(offset){if(!state.data)return;state.offset=Math.max(0,offset||0);await call('article_review_get_page',filters())}
async function loadDocument(){if(!state.data)return;try{const result=await tool('article_review_get_document',{sessionId:state.data.sessionId,pendingPolicy:'proposal'});const value=structured(result);state.finalContent=value.content;renderFinal()}catch(error){showError(error)}}
function replyComment(comment){const reply=window.prompt('Implementation reply',comment.implementationReply||'');if(reply==null||!reply.trim())return;call('article_review_reply_comment',Object.assign(mutationBase(),{commentId:comment.id,implementationReply:reply.trim()}))}
function resolveComment(comment,resolved){call('article_review_resolve_comment',Object.assign(mutationBase(),{commentId:comment.id,resolved}))}
function relevantNavigationItems(){const items=state.data&&state.data.page?state.data.page.items:[];return state.topicId==='all'?items:items.filter(item=>item.matchesTopic)}
document.querySelectorAll('.mode').forEach(item=>item.onclick=()=>{state.mode=item.dataset.mode;render();if(state.mode==='final')loadDocument()});
$('filter').onchange=event=>{state.status=event.target.value;state.offset=0;loadPage(0)};
let searchTimer;$('search').oninput=event=>{state.query=event.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.offset=0;loadPage(0)},250)};
$('focus').onclick=()=>{state.contextMode=state.contextMode==='dim_unrelated'?'hide_unrelated':'dim_unrelated';state.offset=0;state.selected=null;loadPage(0)};
$('acceptVisible').onclick=()=>bulk('accepted');$('rejectVisible').onclick=()=>bulk('rejected');
$('prev').onclick=()=>loadPage(Math.max(0,state.data.page.offset-state.data.page.limit));$('next').onclick=()=>loadPage(state.data.page.offset+state.data.page.limit);
$('form').onsubmit=event=>{event.preventDefault();const hunk=state.data&&state.data.page.items.find(item=>item.id===state.selected),body=$('comment').value.trim();if(!hunk||!body)return;call('article_review_add_comment',Object.assign(mutationBase(),{patchId:hunk.id,topicId:$('commentTopic').value,kind:'review_comment',severity:$('severity').value,body,author:{id:$('reviewer').value.toLowerCase().replace(/W+/g,'-')||'human-reviewer',name:$('reviewer').value||'Human reviewer',role:'human'}}));$('comment').value=''};
document.onkeydown=event=>{if(event.target.matches('input,textarea,select'))return;const items=relevantNavigationItems();if(!items.length)return;let index=Math.max(0,items.findIndex(item=>item.id===state.selected));const keyValue=event.key.toLowerCase();if(keyValue==='j'){state.selected=items[Math.min(items.length-1,index+1)].id;renderHunks();renderComments();$('hunk-'+state.selected)?.scrollIntoView({behavior:'smooth',block:'center'})}else if(keyValue==='k'){state.selected=items[Math.max(0,index-1)].id;renderHunks();renderComments();$('hunk-'+state.selected)?.scrollIntoView({behavior:'smooth',block:'center'})}else if(keyValue==='a'&&state.selected)decide(state.selected,'accepted');else if(keyValue==='r'&&state.selected)decide(state.selected,'rejected');else if(keyValue==='e'&&state.selected){const hunk=state.data.page.items.find(item=>item.id===state.selected);if(hunk)editPatch(hunk)}};
if(INITIAL)apply(INITIAL);
if(!STANDALONE)request('ui/initialize',{appInfo:{name:'Article Review App',version:'1.1.0'},appCapabilities:{availableDisplayModes:['inline','fullscreen']},protocolVersion:'2026-01-26'}).then(result=>{theme(result.hostContext);notify('ui/notifications/initialized',{})}).catch(showError);
