
const INITIAL=__ARTICLE_REVIEW_INITIAL_87f6__,STANDALONE=__ARTICLE_REVIEW_STANDALONE_87f6__;
const state={data:INITIAL,selected:null,mode:'split',status:'all',query:'',topicId:'all',contextMode:'dim_unrelated',offset:0,busy:false,finalContent:null};
const $=id=>document.getElementById(id);let rpcId=1;const pending=new Map();
function key(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random()}
function showError(error){$('error').textContent=error&&error.message?error.message:String(error);$('error').classList.remove('hidden')}
function clearError(){$('error').classList.add('hidden')}
function structured(value){return value&&value.structuredContent?value.structuredContent:value&&value.result&&value.result.structuredContent?value.result.structuredContent:value}
window.addEventListener('message',event=>{const message=event.data;if(!message||message.jsonrpc!=='2.0')return;if(Object.hasOwn(message,'id')&&pending.has(message.id)){const waiter=pending.get(message.id);pending.delete(message.id);message.error?waiter.reject(new Error(message.error.message)):waiter.resolve(message.result)}else if(message.method==='ui/notifications/tool-result')apply(structured(message.params));else if(message.method==='ui/notifications/host-context-changed')theme(message.params)});
function request(method,params){const id=rpcId++;parent.postMessage({jsonrpc:'2.0',id,method,params:params||{}},'*');return new Promise((resolve,reject)=>{pending.set(id,{resolve,reject});setTimeout(()=>{if(pending.delete(id))reject(new Error('Host timeout'))},30000)})}
function notify(method,params){parent.postMessage({jsonrpc:'2.0',method,params:params||{}},'*')}
async function tool(name,args){if(STANDALONE){const token=new URLSearchParams(location.search).get('token');const suffix=token?'?token='+encodeURIComponent(token):'';const response=await fetch('/api/tool'+suffix,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,arguments:args})});const value=await response.json();if(!response.ok||value.isError)throw new Error(value.content&&value.content[0]?value.content[0].text:value.error||'Request failed');return value}const value=await request('tools/call',{name,arguments:args});if(value&&value.isError)throw new Error(value.content&&value.content[0]?value.content[0].text:'Tool failed');return value}
function filters(extra){return Object.assign({sessionId:state.data.sessionId,offset:state.offset,limit:state.data.page.limit,status:state.status,query:state.query,topicId:state.topicId,contextMode:state.contextMode},extra||{})}
async function call(name,args){clearError();document.body.classList.add('busy');try{const result=await tool(name,args);apply(structured(result))}catch(error){showError(error)}finally{document.body.classList.remove('busy')}}
function theme(context){document.body.classList.toggle('dark',context&&context.theme==='dark')}
function apply(data){if(!data||!data.sessionId)return;state.data=data;state.offset=data.page?data.page.offset:state.offset;state.finalContent=null;if(data.activeFilters){state.status=data.activeFilters.status||state.status;state.query=data.activeFilters.query||state.query;state.topicId=data.activeFilters.topicId||state.topicId;state.contextMode=data.activeFilters.contextMode||state.contextMode}$('filter').value=state.status;$('search').value=state.query;if(data.page&&!data.page.items.some(item=>item.id===state.selected))state.selected=(data.page.items.find(item=>item.matchesTopic)||data.page.items[0]||{}).id||null;render();if(state.mode==='final')loadDocument()}
function text(node,value){node.append(document.createTextNode(value||''))}
function button(label,handler,className){const element=document.createElement('button');element.className=className||'mini';element.type='button';element.textContent=label;element.onclick=event=>{event.stopPropagation();handler()};return element}
function topicLabel(id){const item=(state.data&&state.data.topics||[]).find(topic=>topic.id===id);return item?item.label:id}
function mutationBase(){return filters({expectedVersion:state.data.version,idempotencyKey:key()})}
function decide(id,status){call('article_review_set_patch_decision',Object.assign(mutationBase(),{patchId:id,status}))}
function bulk(status){const items=(state.data.page.items||[]).filter(item=>state.topicId==='all'||item.matchesTopic);if(!items.length)return;call('article_review_bulk_decide',Object.assign(mutationBase(),{status,patchIds:items.map(item=>item.id)}))}
function editPatch(hunk){const row=$('hunk-'+hunk.id),existing=$('edit-'+hunk.id);if(existing){existing.remove();return}const wrap=document.createElement('div');wrap.className='editor';wrap.id='edit-'+hunk.id;const area=document.createElement('textarea');area.value=hunk.decision.status==='edited'?(hunk.decision.editedText||''):hunk.afterText;wrap.append(area,button('Save',()=>call('article_review_edit_patch',Object.assign(mutationBase(),{patchId:hunk.id,editedText:area.value}))),button('Cancel',()=>wrap.remove()));row.append(wrap);area.focus()}